import { Inter, Poppins, Libre_Baskerville } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});
const libre = Libre_Baskerville({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-libre-baskerville",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${libre.variable}`}>
      <body>{children}</body>
    </html>
  );
}
